// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "../../src/screen_func/screen4/screen4_func.h"
#define time 600 
///////////////////// VARIABLES ////////////////////
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_bataryTotalContainer;
lv_obj_t * ui_batteryArc;
lv_obj_t * ui_labelbatteryYuzde;
lv_obj_t * ui_arcDeger;
lv_obj_t * ui_batteryTotalValue;
lv_obj_t * ui_Label8;
void ui_event_screen1Ileri(lv_event_t * e);
lv_obj_t * ui_screen1Ileri;
void ui_event_screen1Geri(lv_event_t * e);
lv_obj_t * ui_screen1Geri;
void ui_event_screen1btn(lv_event_t * e);
lv_obj_t * ui_screen1btn;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Label10;
lv_obj_t * ui_TemizGenelContainer;
lv_obj_t * ui_temizsudeger;
lv_obj_t * ui_temizSuArc;
lv_obj_t * ui_labeltsyuzde;
lv_obj_t * ui_temizSuMiktar;
lv_obj_t * ui_KirliGenelContainer;
lv_obj_t * ui_labelKSYuzde;
lv_obj_t * ui_kirliSuDeger;
lv_obj_t * ui_kirliSuArc;
lv_obj_t * ui_kirliSuMiktar;
void ui_event_screen2Geri(lv_event_t * e);
lv_obj_t * ui_screen2Geri;
void ui_event_screen2Ileri(lv_event_t * e);
lv_obj_t * ui_screen2Ileri;
void ui_event_screen2btn(lv_event_t * e);
lv_obj_t * ui_screen2btn;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Label23;
lv_obj_t * ui_fuelPublicTankContainer;
lv_obj_t * ui_Label25;
lv_obj_t * ui_fuelMiktar;
lv_obj_t * ui_fueldeger;
lv_obj_t * ui_fuelArc;
void ui_event_screen3Geri(lv_event_t * e);
lv_obj_t * ui_screen3Geri;
void ui_event_screen3Ileri(lv_event_t * e);
lv_obj_t * ui_screen3Ileri;
void ui_event_screen3btn(lv_event_t * e);
lv_obj_t * ui_screen3btn;

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_Label41;
void ui_event_screen4Geri(lv_event_t * e);
lv_obj_t * ui_screen4Geri;
void ui_event_screen4Add(lv_event_t * e);
lv_obj_t * ui_screen4Add;

lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_[2] = {&ui_img_111_png, &ui_img_2_png};


void create_input_panel(lv_obj_t * parent, const char * roller_options);
///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_screen1Ileri(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, time, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_screen1Geri(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, time, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_screen1btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, time, 0, &ui_Screen4_screen_init);
    }
}
void ui_event_screen2Geri(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, time, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_screen2Ileri(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, time, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_screen2btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, time, 0, &ui_Screen4_screen_init);
    }
}
void ui_event_screen3Geri(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, time, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_screen3Ileri(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, time, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_screen3btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, time, 0, &ui_Screen4_screen_init);
    }
}
void ui_event_screen4Geri(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, time, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_screen4Add(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        create_input_panel(lv_scr_act(), rol);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}



// void ui_event_screen1Ileri(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         lv_obj_add_flag(ui_Screen1, LV_OBJ_FLAG_HIDDEN);  // Şu anki ekranı gizle
//         lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_HIDDEN); // Hedef ekranı göster
//     }
// }

// void ui_event_screen1Geri(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         lv_obj_add_flag(ui_Screen1, LV_OBJ_FLAG_HIDDEN);  // Şu anki ekranı gizle
//         lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_HIDDEN); // Hedef ekranı göster
//     }
// }

// void ui_event_screen2Geri(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         lv_obj_add_flag(ui_Screen2, LV_OBJ_FLAG_HIDDEN);  // Şu anki ekranı gizle
//         lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_HIDDEN); // Hedef ekranı göster
//     }
// }

// void ui_event_screen2Ileri(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         lv_obj_add_flag(ui_Screen2, LV_OBJ_FLAG_HIDDEN);  // Şu anki ekranı gizle
//         lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_HIDDEN); // Hedef ekranı göster
//     }
// }

// void ui_event_screen3Geri(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         lv_obj_add_flag(ui_Screen3, LV_OBJ_FLAG_HIDDEN);  // Şu anki ekranı gizle
//         lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_HIDDEN); // Hedef ekranı göster
//     }
// }

// void ui_event_screen3Ileri(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         lv_obj_add_flag(ui_Screen3, LV_OBJ_FLAG_HIDDEN);  // Şu anki ekranı gizle
//         lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_HIDDEN); // Hedef ekranı göster
//     }
// }

// ///////////////////// SCREENS ////////////////////

// void ui_init(void)
// {
//     lv_disp_t * dispp = lv_disp_get_default();
//     lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
//                                                false, LV_FONT_DEFAULT);
//     lv_disp_set_theme(dispp, theme);

//     ui_Screen1 = lv_obj_create(NULL);  // Screen1'i oluştur
//     ui_Screen2 = lv_obj_create(NULL);  // Screen2'yi oluştur
//     ui_Screen3 = lv_obj_create(NULL);  // Screen3'ü oluştur

//     ui_Screen1_screen_init();
//     ui_Screen2_screen_init();
//     ui_Screen3_screen_init();

//     lv_obj_add_flag(ui_Screen2, LV_OBJ_FLAG_HIDDEN);  // Screen2'yi gizle
//     lv_obj_add_flag(ui_Screen3, LV_OBJ_FLAG_HIDDEN);  // Screen3'ü gizle

//     lv_disp_load_scr(ui_Screen1);  // İlk olarak Screen1'i yükle
// }


