// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Screen4;

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_bataryTotalContainer;
extern lv_obj_t * ui_batteryArc;
extern lv_obj_t * ui_labelbatteryYuzde;
extern lv_obj_t * ui_arcDeger;
extern lv_obj_t * ui_batteryTotalValue;
extern lv_obj_t * ui_Label8;
void ui_event_screen1Ileri(lv_event_t * e);
extern lv_obj_t * ui_screen1Ileri;
void ui_event_screen1Geri(lv_event_t * e);
extern lv_obj_t * ui_screen1Geri;
void ui_event_screen1btn(lv_event_t * e);
extern lv_obj_t * ui_screen1btn;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_TemizGenelContainer;
extern lv_obj_t * ui_temizsudeger;
extern lv_obj_t * ui_temizSuArc;
extern lv_obj_t * ui_labeltsyuzde;
extern lv_obj_t * ui_temizSuMiktar;
extern lv_obj_t * ui_KirliGenelContainer;
extern lv_obj_t * ui_labelKSYuzde;
extern lv_obj_t * ui_kirliSuDeger;
extern lv_obj_t * ui_kirliSuArc;
extern lv_obj_t * ui_kirliSuMiktar;
void ui_event_screen2Geri(lv_event_t * e);
extern lv_obj_t * ui_screen2Geri;
void ui_event_screen2Ileri(lv_event_t * e);
extern lv_obj_t * ui_screen2Ileri;
void ui_event_screen2btn(lv_event_t * e);
extern lv_obj_t * ui_screen2btn;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_fuelPublicTankContainer;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_fuelMiktar;
extern lv_obj_t * ui_fueldeger;
extern lv_obj_t * ui_fuelArc;
void ui_event_screen3Geri(lv_event_t * e);
extern lv_obj_t * ui_screen3Geri;
void ui_event_screen3Ileri(lv_event_t * e);
extern lv_obj_t * ui_screen3Ileri;
void ui_event_screen3btn(lv_event_t * e);
extern lv_obj_t * ui_screen3btn;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label41;
// extern lv_obj_t * ui_Button11;
// void ui_event_button11(lv_event_t * e);
void ui_event_screen4Geri(lv_event_t * e);
extern lv_obj_t * ui_screen4Geri;
void ui_event_screen4Add(lv_event_t * e);
extern lv_obj_t * ui_screen4Add;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_111_png);    // assets/111.png
LV_IMG_DECLARE(ui_img_add_png);    // assets/add.png
LV_IMG_DECLARE(ui_img_down_png);    // assets/down.png
LV_IMG_DECLARE(ui_img_eexit_png);    // assets/eexit.png
LV_IMG_DECLARE(ui_img_delete_png);    // assets/delete.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_tick_png); 




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
