// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -271);
    lv_obj_set_y(ui_Label10, -209);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "WATER MONITOR");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label10, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemizGenelContainer = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_TemizGenelContainer);
    lv_obj_set_width(ui_TemizGenelContainer, 200);
    lv_obj_set_height(ui_TemizGenelContainer, 200);
    lv_obj_set_x(ui_TemizGenelContainer, -70);
    lv_obj_set_y(ui_TemizGenelContainer, -40);
    lv_obj_set_align(ui_TemizGenelContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TemizGenelContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temizsudeger = lv_label_create(ui_TemizGenelContainer);
    lv_obj_set_width(ui_temizsudeger, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temizsudeger, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temizsudeger, 2);
    lv_obj_set_y(ui_temizsudeger, -36);
    lv_obj_set_align(ui_temizsudeger, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temizsudeger, "88");
    lv_obj_set_style_text_color(ui_temizsudeger, lv_color_hex(0x004AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temizsudeger, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temizsudeger, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temizSuArc = lv_arc_create(ui_TemizGenelContainer);
    lv_obj_set_width(ui_temizSuArc, 130);
    lv_obj_set_height(ui_temizSuArc, 150);
    lv_obj_set_x(ui_temizSuArc, 0);
    lv_obj_set_y(ui_temizSuArc, -19);
    lv_obj_set_align(ui_temizSuArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_temizSuArc, 50);
    lv_arc_set_bg_angles(ui_temizSuArc, 275, 265);
    lv_obj_set_style_arc_color(ui_temizSuArc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_temizSuArc, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_temizSuArc, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_temizSuArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_temizSuArc, lv_color_hex(0x004AFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_temizSuArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_temizSuArc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_temizSuArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_temizSuArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_temizSuArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_temizSuArc, LV_OBJ_FLAG_CLICKABLE);

    ui_labeltsyuzde = lv_label_create(ui_TemizGenelContainer);
    lv_obj_set_width(ui_labeltsyuzde, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labeltsyuzde, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labeltsyuzde, 1);
    lv_obj_set_y(ui_labeltsyuzde, -4);
    lv_obj_set_align(ui_labeltsyuzde, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeltsyuzde, "%");
    lv_obj_set_style_text_color(ui_labeltsyuzde, lv_color_hex(0x004AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labeltsyuzde, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeltsyuzde, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temizSuMiktar = lv_label_create(ui_TemizGenelContainer);
    lv_obj_set_width(ui_temizSuMiktar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temizSuMiktar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temizSuMiktar, -4);
    lv_obj_set_y(ui_temizSuMiktar, 70);
    lv_obj_set_align(ui_temizSuMiktar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temizSuMiktar, "TSM");
    lv_obj_set_style_text_color(ui_temizSuMiktar, lv_color_hex(0x004AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temizSuMiktar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temizSuMiktar, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KirliGenelContainer = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_KirliGenelContainer);
    lv_obj_set_width(ui_KirliGenelContainer, 200);
    lv_obj_set_height(ui_KirliGenelContainer, 200);
    lv_obj_set_x(ui_KirliGenelContainer, 70);
    lv_obj_set_y(ui_KirliGenelContainer, -40);
    lv_obj_set_align(ui_KirliGenelContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_KirliGenelContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelKSYuzde = lv_label_create(ui_KirliGenelContainer);
    lv_obj_set_width(ui_labelKSYuzde, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelKSYuzde, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelKSYuzde, 2);
    lv_obj_set_y(ui_labelKSYuzde, -3);
    lv_obj_set_align(ui_labelKSYuzde, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelKSYuzde, "%");
    lv_obj_set_style_text_color(ui_labelKSYuzde, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelKSYuzde, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelKSYuzde, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kirliSuDeger = lv_label_create(ui_KirliGenelContainer);
    lv_obj_set_width(ui_kirliSuDeger, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kirliSuDeger, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kirliSuDeger, 2);
    lv_obj_set_y(ui_kirliSuDeger, -36);
    lv_obj_set_align(ui_kirliSuDeger, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kirliSuDeger, "22");
    lv_obj_set_style_text_color(ui_kirliSuDeger, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kirliSuDeger, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kirliSuDeger, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kirliSuArc = lv_arc_create(ui_KirliGenelContainer);
    lv_obj_set_width(ui_kirliSuArc, 130);
    lv_obj_set_height(ui_kirliSuArc, 150);
    lv_obj_set_x(ui_kirliSuArc, 0);
    lv_obj_set_y(ui_kirliSuArc, -19);
    lv_obj_set_align(ui_kirliSuArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_kirliSuArc, 50);
    lv_arc_set_bg_angles(ui_kirliSuArc, 275, 265);
    lv_obj_set_style_arc_color(ui_kirliSuArc, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_kirliSuArc, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_kirliSuArc, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_kirliSuArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_kirliSuArc, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_kirliSuArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_kirliSuArc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_kirliSuArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_kirliSuArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_kirliSuArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_kirliSuArc, LV_OBJ_FLAG_CLICKABLE);

    ui_kirliSuMiktar = lv_label_create(ui_KirliGenelContainer);
    lv_obj_set_width(ui_kirliSuMiktar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kirliSuMiktar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kirliSuMiktar, -4);
    lv_obj_set_y(ui_kirliSuMiktar, 70);
    lv_obj_set_align(ui_kirliSuMiktar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kirliSuMiktar, "KSM");
    lv_obj_set_style_text_color(ui_kirliSuMiktar, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kirliSuMiktar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kirliSuMiktar, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screen2Geri = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_screen2Geri, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_111_png, NULL);
    lv_obj_set_height(ui_screen2Geri, 64);
    lv_obj_set_width(ui_screen2Geri, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_screen2Geri, -349);
    lv_obj_set_y(ui_screen2Geri, 185);
    lv_obj_set_align(ui_screen2Geri, LV_ALIGN_CENTER);

    ui_screen2Ileri = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_screen2Ileri, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2_png, NULL);
    lv_obj_set_height(ui_screen2Ileri, 64);
    lv_obj_set_width(ui_screen2Ileri, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_screen2Ileri, 343);
    lv_obj_set_y(ui_screen2Ileri, 185);
    lv_obj_set_align(ui_screen2Ileri, LV_ALIGN_CENTER);

    ui_screen2btn = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_screen2btn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_down_png, NULL);
    lv_obj_set_height(ui_screen2btn, 64);
    lv_obj_set_width(ui_screen2btn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_screen2btn, 0);
    lv_obj_set_y(ui_screen2btn, 185);
    lv_obj_set_align(ui_screen2btn, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_screen2Geri, ui_event_screen2Geri, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screen2Ileri, ui_event_screen2Ileri, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screen2btn, ui_event_screen2btn, LV_EVENT_ALL, NULL);

}
