// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bataryTotalContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_bataryTotalContainer);
    lv_obj_set_width(ui_bataryTotalContainer, 300);
    lv_obj_set_height(ui_bataryTotalContainer, 300);
    lv_obj_set_x(ui_bataryTotalContainer, -210);
    lv_obj_set_y(ui_bataryTotalContainer, -20);
    lv_obj_set_align(ui_bataryTotalContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_bataryTotalContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryArc = lv_arc_create(ui_bataryTotalContainer);
    lv_obj_set_width(ui_batteryArc, 230);
    lv_obj_set_height(ui_batteryArc, 230);
    lv_obj_set_x(ui_batteryArc, 0);
    lv_obj_set_y(ui_batteryArc, -20);
    lv_obj_set_align(ui_batteryArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_batteryArc, 100);
    lv_arc_set_bg_angles(ui_batteryArc, 271, 269);
    lv_obj_set_style_arc_color(ui_batteryArc, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_batteryArc, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_batteryArc, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_batteryArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_batteryArc, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_batteryArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_batteryArc, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_batteryArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_batteryArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batteryArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_batteryArc, LV_OBJ_FLAG_CLICKABLE);

    ui_labelbatteryYuzde = lv_label_create(ui_bataryTotalContainer);
    lv_obj_set_width(ui_labelbatteryYuzde, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelbatteryYuzde, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelbatteryYuzde, 5);
    lv_obj_set_y(ui_labelbatteryYuzde, 10);
    lv_obj_set_align(ui_labelbatteryYuzde, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelbatteryYuzde, "%");
    lv_obj_set_style_text_color(ui_labelbatteryYuzde, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelbatteryYuzde, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelbatteryYuzde, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcDeger = lv_label_create(ui_bataryTotalContainer);
    lv_obj_set_width(ui_arcDeger, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_arcDeger, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_arcDeger, 5);
    lv_obj_set_y(ui_arcDeger, -20);
    lv_obj_set_align(ui_arcDeger, LV_ALIGN_CENTER);
    lv_label_set_text(ui_arcDeger, "78");
    lv_obj_set_style_text_color(ui_arcDeger, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_arcDeger, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_arcDeger, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryTotalValue = lv_label_create(ui_bataryTotalContainer);
    lv_obj_set_width(ui_batteryTotalValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batteryTotalValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batteryTotalValue, -1);
    lv_obj_set_y(ui_batteryTotalValue, 130);
    lv_obj_set_align(ui_batteryTotalValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batteryTotalValue, "arcToplam");
    lv_obj_set_style_text_color(ui_batteryTotalValue, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_batteryTotalValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batteryTotalValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -263);
    lv_obj_set_y(ui_Label8, -209);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "BATTERY MONITOR");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label8, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screen1Ileri = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_screen1Ileri, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2_png, NULL);
    lv_obj_set_height(ui_screen1Ileri, 64);
    lv_obj_set_width(ui_screen1Ileri, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_screen1Ileri, 347);
    lv_obj_set_y(ui_screen1Ileri, 185);
    lv_obj_set_align(ui_screen1Ileri, LV_ALIGN_CENTER);

    ui_screen1Geri = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_screen1Geri, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_111_png, NULL);
    lv_obj_set_height(ui_screen1Geri, 64);
    lv_obj_set_width(ui_screen1Geri, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_screen1Geri, -367);
    lv_obj_set_y(ui_screen1Geri, 185);
    lv_obj_set_align(ui_screen1Geri, LV_ALIGN_CENTER);

    ui_screen1btn = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_screen1btn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_down_png, NULL);
    lv_obj_set_height(ui_screen1btn, 64);
    lv_obj_set_width(ui_screen1btn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_screen1btn, 0);
    lv_obj_set_y(ui_screen1btn, 185);
    lv_obj_set_align(ui_screen1btn, LV_ALIGN_CENTER);
    
    lv_obj_add_event_cb(ui_screen1Ileri, ui_event_screen1Ileri, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screen1Geri, ui_event_screen1Geri, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screen1btn, ui_event_screen1btn, LV_EVENT_ALL, NULL);

}
