// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -280);
    lv_obj_set_y(ui_Label23, -212);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "FUEL MONITOR");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label23, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label23, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelPublicTankContainer = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_fuelPublicTankContainer);
    lv_obj_set_width(ui_fuelPublicTankContainer, 300);
    lv_obj_set_height(ui_fuelPublicTankContainer, 300);
    lv_obj_set_x(ui_fuelPublicTankContainer, -210);
    lv_obj_set_y(ui_fuelPublicTankContainer, -20);
    lv_obj_set_align(ui_fuelPublicTankContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fuelPublicTankContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_fuelPublicTankContainer);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 5);
    lv_obj_set_y(ui_Label25, 10);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "%");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelMiktar = lv_label_create(ui_fuelPublicTankContainer);
    lv_obj_set_width(ui_fuelMiktar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fuelMiktar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fuelMiktar, -1);
    lv_obj_set_y(ui_fuelMiktar, 130);
    lv_obj_set_align(ui_fuelMiktar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fuelMiktar, "650");
    lv_obj_set_style_text_color(ui_fuelMiktar, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fuelMiktar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fuelMiktar, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fueldeger = lv_label_create(ui_fuelPublicTankContainer);
    lv_obj_set_width(ui_fueldeger, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fueldeger, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fueldeger, 5);
    lv_obj_set_y(ui_fueldeger, -20);
    lv_obj_set_align(ui_fueldeger, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fueldeger, "65");
    lv_obj_set_style_text_color(ui_fueldeger, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fueldeger, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fueldeger, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelArc = lv_arc_create(ui_fuelPublicTankContainer);
    lv_obj_set_width(ui_fuelArc, 230);
    lv_obj_set_height(ui_fuelArc, 230);
    lv_obj_set_x(ui_fuelArc, 0);
    lv_obj_set_y(ui_fuelArc, -20);
    lv_obj_set_align(ui_fuelArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_fuelArc, 50);
    lv_arc_set_bg_angles(ui_fuelArc, 271, 269);
    lv_obj_set_style_arc_color(ui_fuelArc, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_fuelArc, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_fuelArc, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_fuelArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_fuelArc, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_fuelArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_fuelArc, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_fuelArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_fuelArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuelArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_fuelArc, LV_OBJ_FLAG_CLICKABLE);

    ui_screen3Geri = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_screen3Geri, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_111_png, NULL);
    lv_obj_set_height(ui_screen3Geri, 64);
    lv_obj_set_width(ui_screen3Geri, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_screen3Geri, -351);
    lv_obj_set_y(ui_screen3Geri, 185);
    lv_obj_set_align(ui_screen3Geri, LV_ALIGN_CENTER);

    ui_screen3Ileri = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_screen3Ileri, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2_png, NULL);
    lv_obj_set_height(ui_screen3Ileri, 64);
    lv_obj_set_width(ui_screen3Ileri, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_screen3Ileri, 343);
    lv_obj_set_y(ui_screen3Ileri, 185);
    lv_obj_set_align(ui_screen3Ileri, LV_ALIGN_CENTER);

    ui_screen3btn = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_screen3btn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_down_png, NULL);
    lv_obj_set_height(ui_screen3btn, 64);
    lv_obj_set_width(ui_screen3btn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_screen3btn, 0);
    lv_obj_set_y(ui_screen3btn, 185);
    lv_obj_set_align(ui_screen3btn, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_screen3Geri, ui_event_screen3Geri, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screen3Ileri, ui_event_screen3Ileri, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screen3btn, ui_event_screen3btn, LV_EVENT_ALL, NULL);

}
