// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// extern int button_width;  
// extern int button_height;
// extern int spacing_x;
// extern int spacing_y;

const int button_width = 64;  // Define the button width
const int button_height = 32; // Define the button height
const int spacing_x = 10;     // Define horizontal spacing
const int spacing_y = 10;     // Define vertical spacing

void ui_Screen4_screen_init(void)
{
    // İlk satırın başlangıç noktası
    int start_x = -((button_width * 5 + spacing_x * 4) / 2) + button_width / 2;
    int start_y = -((button_height * 2 + spacing_y) / 2) + button_height / 2;
    
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, -271);
    lv_obj_set_y(ui_Label41, -200);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "BUTTON MONITOR");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label41, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label41, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label41, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screen4Geri = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_screen4Geri, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_down_png, NULL);
    lv_obj_set_height(ui_screen4Geri, 64);
    lv_obj_set_width(ui_screen4Geri, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_screen4Geri, 0);
    lv_obj_set_y(ui_screen4Geri, 185);
    lv_obj_set_align(ui_screen4Geri, LV_ALIGN_CENTER);

    ui_screen4Add = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_screen4Add, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_add_png, NULL);
    lv_obj_set_height(ui_screen4Add, 64);
    lv_obj_set_width(ui_screen4Add, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_screen4Add, 300);
    lv_obj_set_y(ui_screen4Add, -200);
    lv_obj_set_align(ui_screen4Add, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_screen4Add, ui_event_screen4Add, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screen4Geri, ui_event_screen4Geri, LV_EVENT_ALL, NULL);

}
