/// ARB-based internationalization support for 'en' and 'tr' locales.
/// Generated from lib/core/localization/arb/app_*.arb files.
///
/// This class provides access to localized strings. In production, this would be
/// auto-generated by the Flutter gen-l10n tool. For now, it's a stub that shows
/// how localization will be structured.
///
/// TODO: Implement string lookups from generated ARB files
class AppLocalizations {
  final String locale;

  AppLocalizations(this.locale);

  /// Application title
  String get appTitle => 'Smell Device';

  /// Connection screen
  String get connectDevice => 'Connect to Device';
  String get scanning => 'Scanning...';
  String get noDevicesFound => 'No devices found';

  /// Smells management
  String get smells => 'Smells';
  String get addSmell => 'Add Smell';
  String get smellName => 'Smell Name';

  /// Schedules management
  String get schedules => 'Schedules';
  String get addSchedule => 'Add Schedule';
  String get day => 'Day';
  String get startTime => 'Start Time';
  String get endTime => 'End Time';
  String get selectSmell => 'Select Smell';

  /// Settings
  String get settings => 'Settings';
  String get language => 'Language';
  String get wipeAllData => 'Wipe All Data';

  /// Common actions
  String get confirm => 'Confirm';
  String get cancel => 'Cancel';
  String get save => 'Save';
  String get delete => 'Delete';
}

// TODO: Implement delegate and localization setup
// This will be auto-generated by `flutter gen-l10n` once ARB files are complete
